# Site settings
title: 易 · 生
SEOTitle: 易 · 生
header-img: "/cdn.isheng.top/green.jpg"
email: zengjiean@gmail.com
description: "曾杰安|易·生"
keyword: ""
url: "http://www.isheng.top"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'
cdn: "cdn.isheng.top"



# SNS settings
RSS: true
weibo_username:     love1me1
zhihu_username:     isheng5
github_username:    isheng5
#twitter_username:  huxpro
facebook_username:



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:211 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate,jekyll-feed]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: isheng5
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing
# livere
livere_data_uid: MTAyMC8yOTUyNy82MDk1


# Analytics settings
# Baidu Analytics
ba_track_id: 3adf1da998f6e849e695c8b61d1d5646
# Google Analytics
ga_track_id: 'UA-80832492-1'            # Format: UA-xxxxxx-xx
ga_domain: www.isheng.top



# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "人生从不是一场马拉松！"
sidebar-avatar: //{{ site.cdn }}/favicon.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: false
friends: [
    {
        title: "woodcoding",
        href: "http://woodcoding.com"
    },{
        title: "FreeLoop",
        href: "http://dabiaoge.coding.me"
    }
]

#My tools
#图片最好是100*100的
tools: [
    {
        name: "Github",
        href: "http://www.github.com",
        description: "全球最大的程序员交友社区，以代码会友！",
        img: "http://cdn.isheng.top/tools/img/github.png"
    },{
        name: "360公共库",
        href: "http://libs.useso.com/",
        description: "360的这个公共服务库真的好棒，用来加速字体",
        img: "http://cdn.isheng.top/tools/img/360.png"
    },{
        name: "百度CDN",
        href: "http://su.baidu.com/",
        description: "加速效果不错，还可以免费使用。",
        img: "http://cdn.isheng.top/tools/img/baidu.png"
    },{
        name: "七牛",
        href: "http://www.qiniu.com/",
        description: "感谢七牛，本站所有的图片都在七牛上。",
        img: "http://cdn.isheng.top/tools/img/qiniu.png"
    },{
        name: "Coding",
        href: "http://www.coding.net/",
        description: "中国的github吧，我博客就是在这上面。",
        img: "http://cdn.isheng.top/tools/img/coding.png"
    },{
        name: "知乎",
        href: "http://www.zhihu.com/",
        description: "这个必须喜欢，太多的知识了，必备良品",
        img: "http://cdn.isheng.top/tools/img/zhihu.png"
    }
]
